let Questions = [
    { numb: 1, question: "What is the capital of France?", answer: "B. Paris", options: ["A. Lyon", "B. Paris", "C. Marseille", "D. Nice"] },
    { numb: 2, question: "Who wrote 'Hamlet'?", answer: "A. William Shakespeare", options: ["A. William Shakespeare", "B. Charles Dickens", "C. Jane Austen", "D. J.K. Rowling"] },
    { numb: 3, question: "Which planet is known as the Red Planet?", answer: "B. Mars", options: ["A. Venus", "B. Mars", "C. Jupiter", "D. Saturn"] },
    { numb: 4, question: "In which year did World War II end?", answer: "D. 1945", options: ["A. 1939", "B. 1941", "C. 1944", "D. 1945"] },
    { numb: 5, question: "Who painted the 'Starry Night'?", answer: "A. Vincent van Gogh", options: ["A. Vincent van Gogh", "B. Claude Monet", "C. Pablo Picasso", "D. Salvador Dalí"] },
    { numb: 6, question: "What is the largest mammal?", answer: "C. Blue Whale", options: ["A. Elephant", "B. Giraffe", "C. Blue Whale", "D. Hippopotamus"] },
    { numb: 7, question: "How many continents are there?", answer: "A. Seven", options: ["A. Seven", "B. Six", "C. Five", "D. Eight"] },
    { numb: 8, question: "What is the tallest mountain in the world?", answer: "D. Mount Everest", options: ["A. K2", "B. Kangchenjunga", "C. Lhotse", "D. Mount Everest"] },
    { numb: 9, question: "Who developed the theory of relativity?", answer: "C. Albert Einstein", options: ["A. Isaac Newton", "B. Nikola Tesla", "C. Albert Einstein", "D. Galileo Galilei"] },
    { numb: 10, question: "What is the largest desert in the world?", answer: "A. Sahara", options: ["A. Sahara", "B. Gobi", "C. Arabian", "D. Kalahari"] },
    { numb: 11, question: "Which language has the most native speakers?", answer: "C. Mandarin Chinese", options: ["A. English", "B. Spanish", "C. Mandarin Chinese", "D. Hindi"] },
    { numb: 12, question: "What is the hardest substance in the human body?", answer: "B. Tooth enamel", options: ["A. Bone", "B. Tooth enamel", "C. Cartilage", "D. Muscle"] },
    { numb: 13, question: "Which organ is responsible for pumping blood?", answer: "D. Heart", options: ["A. Brain", "B. Lungs", "C. Liver", "D. Heart"] },
    { numb: 14, question: "What is the most spoken language in Brazil?", answer: "A. Portuguese", options: ["A. Portuguese", "B. Spanish", "C. English", "D. French"] },
    { numb: 15, question: "What is the primary ingredient in guacamole?", answer: "C. Avocado", options: ["A. Tomato", "B. Lime", "C. Avocado", "D. Onion"] },
    { numb: 16, question: "Who invented the telephone?", answer: "A. Alexander Graham Bell", options: ["A. Alexander Graham Bell", "B. Thomas Edison", "C. Nikola Tesla", "D. Guglielmo Marconi"] },
    { numb: 17, question: "What is the smallest planet in our solar system?", answer: "B. Mercury", options: ["A. Mars", "B. Mercury", "C. Venus", "D. Earth"] },
    { numb: 18, question: "What is the capital of Australia?", answer: "C. Canberra", options: ["A. Sydney", "B. Melbourne", "C. Canberra", "D. Brisbane"] },
    { numb: 19, question: "Which element has the symbol 'Fe'?", answer: "B. Iron", options: ["A. Lead", "B. Iron", "C. Fluorine", "D. Zinc"] },
    { numb: 20, question: "Who is known as the 'Father of Computers'?", answer: "A. Charles Babbage", options: ["A. Charles Babbage", "B. Alan Turing", "C. Bill Gates", "D. Steve Jobs"] },
    { numb: 21, question: "How many colors are in a rainbow?", answer: "B. Seven", options: ["A. Six", "B. Seven", "C. Eight", "D. Nine"] },
    { numb: 22, question: "What is the capital city of Egypt?", answer: "A. Cairo", options: ["A. Cairo", "B. Alexandria", "C. Luxor", "D. Giza"] },
    { numb: 23, question: "What is the boiling point of water?", answer: "B. 100°C", options: ["A. 90°C", "B. 100°C", "C. 120°C", "D. 80°C"] },
    { numb: 24, question: "Which country hosted the 2016 Summer Olympics?", answer: "D. Brazil", options: ["A. China", "B. Russia", "C. Japan", "D. Brazil"] },
    { numb: 25, question: "What is the largest organ in the human body?", answer: "A. Skin", options: ["A. Skin", "B. Liver", "C. Brain", "D. Heart"] },
    { numb: 26, question: "What is the name of the Greek god of war?", answer: "C. Ares", options: ["A. Zeus", "B. Apollo", "C. Ares", "D. Hermes"] },
    { numb: 27, question: "How many sides does a hexagon have?", answer: "B. Six", options: ["A. Five", "B. Six", "C. Seven", "D. Eight"] },
    { numb: 28, question: "Who was the first person to walk on the moon?", answer: "A. Neil Armstrong", options: ["A. Neil Armstrong", "B. Buzz Aldrin", "C. Michael Collins", "D. Yuri Gagarin"] },
    { numb: 29, question: "What is the largest island in the world?", answer: "A. Greenland", options: ["A. Greenland", "B. Borneo", "C. Madagascar", "D. New Guinea"] },
    { numb: 30, question: "What is the main ingredient in sushi?", answer: "C. Rice", options: ["A. Fish", "B. Seaweed", "C. Rice", "D. Soy Sauce"] }

]
